"""Cat

Revision ID: 59830dd2e470
Revises: afb8e3ecf776
Create Date: 2024-07-14 02:29:27.840011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59830dd2e470'
down_revision: Union[str, None] = 'afb8e3ecf776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('technic', sa.Column('cat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'technic', 'category', ['cat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'technic', type_='foreignkey')
    op.drop_column('technic', 'cat_id')
    op.drop_table('category')
    # ### end Alembic commands ###
